### ISSUE TITLE
Vary header

### ISSUE THREAD

**Issue by avengerpenguin** [bbc/flashheart#23]
Any plans to support the Vary header? We're using https://github.com/gitterHQ/request-http-cache precisely for that reason, but could adopt this more featured client if there were good support for the vary header and stale-if-error.

**Comment by robinjmurphy** [comment]
Hi @avengerpenguin. The caching is super simple at the minute. We vary on _all_ headers except the ones manually listed in the [`doNotVary`](https://github.com/bbc/flashheart#caching) array as this was the simplest implementation we could think of.

Is this something you'd be up for helping out with? If not, we can leave this issue here to look at in the future.

**Comment by avengerpenguin** [comment]
I'm not sure what the benefit would be to add it to a bespoke library here if I have something working with a more mature library already out there. I think the request-extensible is a pretty good approach too to allow more composition of ideas rather than having to choose from a multitude of wrapper libraries, each of which has some but not all of the features you want.

**Comment by robinjmurphy** [comment]
Cool. In which case looks like maybe the flashheart approach isn't for you.
