### ISSUE TITLE
Can it be configured to retry on 400 errors?

### ISSUE THREAD

**Issue by tgoldenberg** [bbc/flashheart#54]
My use case is that I want to retry until a 200 status code is received (this is because the 200 code depends on another data set turning from "pending" to "approved"). Is this possible with this library? It seems like this would be a straightforward feature to add, so I am curious.

**Comment by robinjmurphy** [comment]
Hi @tgoldenberg!

We haven't implemented retries on 4XX errors, only 5XX errors.

This is because in the general case a 4XX error indicates a client error. Making the exact same request again is unlikely to result in a different response.

If you'd like to implement retries for non-5XX status codes then I'd suggest using the retry library directly https://github.com/tim-kos/node-retry. You can inspect the status code on Flashheart errors with `err.statusCode`.

```js
'use strict';

const client = require('flashheart').createClient({
  logger: console
});
const retry = require('retry');

const getWithRetries = (url, cb) => {
  const operation = retry.operation({
    retries: 2
  });

  operation.attempt((i) => {
    client.get(url, (err, body) => {
      if (err && err.statusCode === 400 && operation.retry(err)) {
        return;
      }

      cb(err, body);
    });
  });
};

getWithRetries('http://httpstat.us/400', (err, body) => {
  if (err) {
    return console.error(err.message);
  }

  console.log(body)
});

```
